CREATE TABLE perf (
       ID INTEGER PRIMARY KEY,
       l2_reg REAL,
       learning_rate REAL,
       max_epochs INT,
       min_epochs INT,
       momentum REAL,
       n_hidden_layers INT,
       n_hidden_units INT,
       normalize INT,
       patience INT,
       REWEIGHT INT,
       AUC real,
       AUC_weighted real,
       fmeasure real,
       fmeasure_weighted real,
       precision real,
       precision_weighted real,
       recall real,
       recall_weighted real,
       significance real,
       early_stop_metric text
);
